version: '3.8'
services:
  web-nginx:
      build:
        context: .
        dockerfile: Dockerfile.nginx
      ports:
        - "80:80"
        - "443:443"

  leare-int:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "5000:5000"
      volumes:
        - .:/app