version: '3.8'
services:
  int-rp:
      build:
        context: .
        dockerfile: Dockerfile.nginx
      ports:
        - "3048:3048"
        - "3047:3047"
      networks:
        - leare-network

  leare-int:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "5000:5000"
      volumes:
        - .:/app
      networks:
        - leare-network

networks:
  leare-network:
    external: true